version: '3.4'

services:
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
  backend:
    image: backend
    build:
      context: backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3001:3001
      - 9230:9230
    command: ["node", "--inspect=0.0.0.0:9230", "index.js"]
