version: '3.4'

services:
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
  backend:
    image: backend
    build:
      context: backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: devinch
      DB_PASSWORD: devinch
      DB_NAME: devinch
    ports:
      - 3001:3001
    links:
      - db
    depends_on:
      - db
    volumes:
      - './backend:/src'
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=devinch
      - POSTGRES_PASSWORD=devinch
    ports:
      - '15432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local

